### ISSUE TITLE
Race conditions when multiple XBlocks are in a single unit

### ISSUE THREAD

**Issue by Agrendalath** [openedx/xblock-lti-consumer#379]
There is a race condition when there are multiple LTI Consumer XBlocks in a single unit. The first block has a correct LTI ID, and the second one has an incorrect one. I didn't change anything between these screenshots - I only refreshed the page.
<details><summary>The first refresh</summary>
<img src="https://github.com/openedx/xblock-lti-consumer/assets/3189670/c151f516-7b85-420f-a651-b27ac98f7fcb"/>
</details> 

<details><summary>The second refresh</summary>
<img src="https://github.com/openedx/xblock-lti-consumer/assets/3189670/9a89d0de-d3e5-47c1-aa85-f1778bcf6878"/>
</details> 

_Originally posted by @Agrendalath in https://github.com/openedx/xblock-lti-consumer/issues/378#issuecomment-1572134893_

**Update:** we have [the solution](https://github.com/openedx/xblock-lti-consumer/issues/379#issuecomment-1739458776), but we still need to update the docs.

**Comment by RafayGhafoor** [comment]
@Agrendalath, The error is from the lti_url i.e., https://saltire.lti.app/tool and doesn't occur when the url used is from the [docs](https://github.com/openedx/xblock-lti-consumer#lti-11) i.e., https://lti.tools/saltire/tp

I have checked the network logs and the requests propagate correctly in the right manner from the launch_handler, the resource ids are sent correct, similarly the post request going to the [Saltire LTI](https://saltire.lti.app/tool) for registering the event is also correct but the responses received from them always contain the same resource id, so all the verification results are basically the same. This seems like a bug on the saltire lti app tool which is not sending the responses in correct way.

**Comment by navinkarkera** [comment]
@RafayGhafoor Just to be certain, the problem will be solved if we use https://lti.tools/saltire/tp as the lti_url?

**Comment by RafayGhafoor** [comment]
yes, that's right.

**Comment by Agrendalath** [comment]
@RafayGhafoor, https://saltire.lti.app/ is a newer page version (with LTI 1.3 support), so we should contact them about this bug. I'll leave the details in [the Jira ticket](https://tasks.opencraft.com/browse/BB-7902) (private link).

**Comment by Agrendalath** [comment]
Update: Stephen from [SPV Software Products](https://spvsoftwareproducts.com/) resolved this by adding an option to turn off page refreshes. We can use it through the query param: `https://saltire.lti.app/tool?norefresh`.

The only remaining step here is updating the docs.
