### ISSUE TITLE
Previously supported custom parameters not passing validation

### ISSUE THREAD

**Issue by alangsto** [openedx/xblock-lti-consumer#410]
https://github.com/openedx/xblock-lti-consumer/pull/392 introduced a breaking change that prevents previously allowed custom parameters from passing validation. 

Example of custom parameter that now does not pass validation: 

`["next=something?repo=https://github.com/org/repo?folder=/home/user&branch=main"]`

Changes to the custom parameter validation should be backwards compatible, and account for cases like this where the user passes in a single string.

**Comment by kuipumu** [comment]
@alangsto I created a PR that should address this issue https://github.com/openedx/xblock-lti-consumer/pull/412, this should be loose enough to allow any kind on key-pair value has a custom parameter.

**Comment by Faraz32123** [comment]
closing this issue in favor of this PR: https://github.com/openedx/xblock-lti-consumer/pull/412
