### ISSUE TITLE
Remove xblockutils package

### ISSUE THREAD

**Issue by farhan** [openedx/xblock-lti-consumer#414]
Parent ticket: https://github.com/openedx/axim-engineering/issues/915

This repository is using the [xblock-utils](https://github.com/openedx/xblock-utils/) package which has been deprecated and migrated to within the xblock package.

In this ticket, we will:
```[tasklist]
### Tasks
- [x] Make sure the repository is using xblock [version 1.8.1](https://github.com/openedx/XBlock/releases/tag/xblock-1.8.0) or above. Upgrade the version if required, preferably via the `make upgrade` command.
- [x] Remove the `xblock-utils` package
- [x] Find and replace all the `xblockutils.*` imports with `xblock.utils.*`
- [x] Make sure all the test cases are passing
- [x] Test the xblock
```

**Comment by farhan** [comment]
PR: https://github.com/openedx/xblock-lti-consumer/pull/417

**Comment by feanil** [comment]
PR has been merged and published to PyPI
